// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASbIjWgOS0i-65Js0TrJJTyj-8azO5fDk',
    appId: '1:553255490272:web:781a52f1fa0037bf51b685',
    messagingSenderId: '553255490272',
    projectId: 'twezimbeapp',
    authDomain: 'twezimbeapp.firebaseapp.com',
    storageBucket: 'twezimbeapp.firebasestorage.app',
    measurementId: 'G-3E0YG9T4S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoHjCGhUl2bISAdthQmJz0E4OxXf1iNZY',
    appId: '1:553255490272:android:7db729f71324c04c51b685',
    messagingSenderId: '553255490272',
    projectId: 'twezimbeapp',
    storageBucket: 'twezimbeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJlPNcGpHgh4ja3BzIzWZflfup-uEx3Y',
    appId: '1:553255490272:ios:e6e13d2097938b7451b685',
    messagingSenderId: '553255490272',
    projectId: 'twezimbeapp',
    storageBucket: 'twezimbeapp.firebasestorage.app',
    iosBundleId: 'com.example.twezimbeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJlPNcGpHgh4ja3BzIzWZflfup-uEx3Y',
    appId: '1:553255490272:ios:e6e13d2097938b7451b685',
    messagingSenderId: '553255490272',
    projectId: 'twezimbeapp',
    storageBucket: 'twezimbeapp.firebasestorage.app',
    iosBundleId: 'com.example.twezimbeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASbIjWgOS0i-65Js0TrJJTyj-8azO5fDk',
    appId: '1:553255490272:web:44551f5c1128cee451b685',
    messagingSenderId: '553255490272',
    projectId: 'twezimbeapp',
    authDomain: 'twezimbeapp.firebaseapp.com',
    storageBucket: 'twezimbeapp.firebasestorage.app',
    measurementId: 'G-4K4WJ71GKC',
  );
}
